import { accountItems, financialItems, helpItems } from "@/lib/setting/settings";
import SettingsGroup from "../../components/settings/SettingsGroup";
import ProfileNavbar from "@/components/profile/ProfileNavbar";


const SettingsPage: React.FC = () => {
  return (
    <div className="h-full flex flex-col">
        <ProfileNavbar title="Settings" />
      <div className="flex-1 w-full bg-white md:rounded-2xl  mt-0 md:mt-8 overflow-hidden flex flex-col">
        <SettingsGroup heading="Your account" items={accountItems} />
        <SettingsGroup heading="Financials" items={financialItems} />
        <SettingsGroup heading="Help Center" items={helpItems} />
        <div className="flex items-center justify-between px-6 py-8 mt-auto">
          <button className="text-red-500 font-medium">Sign out</button>
          <button className="bg-blue-600 text-white rounded-full px-12 py-2 font-semibold shadow hover:bg-blue-700 transition">Save</button>
        </div>
      </div>
      <div className="h-20"/>
    </div>
  );
};

export default SettingsPage; 



{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYzY4NDU1My1jMDRkLTRkMGItOWE4NS0zN2Q3MGNiMmQ0YzUiLCJleHAiOjE3NDcyMTI1NTMsImlhdCI6MTc0NzIxMjI1MywiYXVkIjoicW9naXRhOmF1dGg6YWNjZXNzIiwiaXNzIjoicW9naXRhIiwiaXNfdmVyaWZpZWQiOnRydWUsImlzX29uYm9hcmRlZCI6dHJ1ZX0.MaaS3klbzmgIqtjqwK3sLk44qPkGFIt0h-5jrZDVcaQ",
  "accessExp": 1747212553457,
  "user": {
    "email": "samy.ayadi@gauss-enterprise.com",
    "account": "Samy Ayadi",
    "company": "Gauss",
    "coc": "89786084700028",
    "country": "FR",
    "countryOfRegistration": "FR",
    "currency": "EUR",
    "delay": 7,
    "iban": null,
    "bic": null,
    "metadata": {},
    "qid": "1c684553-c04d-4d0b-9a85-37d70cb2d4c5",
    "emails": [
      {
        "email": "samy.ayadi@gauss-enterprise.com",
        "isPrimary": true,
        "isVerified": false,
        "qid": "a5433bbe-afb6-4d98-b980-1f958d158334"
      }
    ],
    "isVerified": true,
    "walletQid": "635a92ec-653e-4ccc-bf65-fb1cf73caf69",
    "network": {
      "code": "E2N2Q",
      "kickback": "0.00",
      "kickbackCurrency": "EUR",
      "value": "0.00",
      "valueCurrency": "EUR",
      "end": null,
      "commission": null,
      "limit": "999999999.00",
      "limitCurrency": "EUR",
      "qid": "fd866b39-3743-4aba-ae0c-790fbe9b8074"
    },
    "membership": null,
    "createdAt": 1741137545996,
    "updatedAt": 1747212084751,
    "insuranceRate": "0.0000",
    "buyingCountries": [
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "GR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK"
    ],
    "shippingCountries": [
      "AF",
      "AX",
      "AL",
      "DZ",
      "AS",
      "AD",
      "AO",
      "AI",
      "AQ",
      "AG",
      "AR",
      "AM",
      "AW",
      "AU",
      "AT",
      "AZ",
      "BS",
      "BH",
      "BD",
      "BB",
      "BY",
      "BE",
      "BZ",
      "BJ",
      "BM",
      "BT",
      "BO",
      "BQ",
      "BA",
      "BW",
      "BV",
      "BR",
      "IO",
      "BN",
      "BG",
      "BF",
      "BI",
      "CV",
      "KH",
      "CM",
      "CA",
      "KY",
      "CF",
      "TD",
      "CL",
      "CN",
      "CX",
      "CC",
      "CO",
      "KM",
      "CG",
      "CD",
      "CK",
      "CR",
      "CI",
      "HR",
      "CU",
      "CW",
      "CY",
      "CZ",
      "DK",
      "DJ",
      "DM",
      "DO",
      "EC",
      "EG",
      "SV",
      "GQ",
      "ER",
      "EE",
      "SZ",
      "ET",
      "FK",
      "FO",
      "FJ",
      "FI",
      "FR",
      "GF",
      "PF",
      "TF",
      "GA",
      "GM",
      "GE",
      "DE",
      "GH",
      "GI",
      "GR",
      "GL",
      "GD",
      "GP",
      "GU",
      "GT",
      "GG",
      "GN",
      "GW",
      "GY",
      "HT",
      "HM",
      "VA",
      "HN",
      "HK",
      "HU",
      "IS",
      "IN",
      "ID",
      "IR",
      "IQ",
      "IE",
      "IM",
      "IL",
      "IT",
      "JM",
      "JP",
      "JE",
      "JO",
      "KZ",
      "KE",
      "KI",
      "KW",
      "KG",
      "LA",
      "LV",
      "LB",
      "LS",
      "LR",
      "LY",
      "LI",
      "LT",
      "LU",
      "MO",
      "MG",
      "MW",
      "MY",
      "MV",
      "ML",
      "MT",
      "MH",
      "MQ",
      "MR",
      "MU",
      "YT",
      "MX",
      "FM",
      "MD",
      "MC",
      "MN",
      "ME",
      "MS",
      "MA",
      "MZ",
      "MM",
      "NA",
      "NR",
      "NP",
      "NL",
      "NC",
      "NZ",
      "NI",
      "NE",
      "NG",
      "NU",
      "NF",
      "KP",
      "MK",
      "MP",
      "NO",
      "OM",
      "PK",
      "PW",
      "PS",
      "PA",
      "PG",
      "PY",
      "PE",
      "PH",
      "PN",
      "PL",
      "PT",
      "PR",
      "QA",
      "RE",
      "RO",
      "RU",
      "RW",
      "BL",
      "SH",
      "KN",
      "LC",
      "MF",
      "PM",
      "VC",
      "WS",
      "SM",
      "ST",
      "SA",
      "SN",
      "RS",
      "SC",
      "SL",
      "SG",
      "SX",
      "SK",
      "SI",
      "SB",
      "SO",
      "ZA",
      "GS",
      "KR",
      "SS",
      "ES",
      "LK",
      "SD",
      "SR",
      "SJ",
      "SE",
      "CH",
      "SY",
      "TW",
      "TJ",
      "TZ",
      "TH",
      "TL",
      "TG",
      "TK",
      "TO",
      "TT",
      "TN",
      "TR",
      "TM",
      "TC",
      "TV",
      "UG",
      "UA",
      "AE",
      "GB",
      "UM",
      "US",
      "UY",
      "UZ",
      "VU",
      "VE",
      "VN",
      "VG",
      "VI",
      "WF",
      "EH",
      "YE",
      "ZM",
      "ZW"
    ],
    "sellerDistributionChannels": [
      "ECOMMERCE",
      "MARKETPLACES",
      "PHYSICAL_STORES"
    ],
    "sellingCountries": [],
    "completedShipWithQogitaOnboarding": false,
    "mov": "0.00",
    "accountNumber": null,
    "sortCode": null,
    "routingNumber": null,
    "fee": "0.000",
    "phone": "+33785745479",
    "callingCode": "+33",
    "lineNumber": "785745479",
    "isPhoneVerified": true,
    "twilioPhoneLookup": {
      "carrier": {
        "name": "Orange",
        "type": "mobile",
        "errorCode": null,
        "mobileCountryCode": "208",
        "mobileNetworkCode": "01"
      }
    },
    "sellerStatus": "ACTIVE",
    "isEmailVerified": true,
    "isWarehouseUser": false,
    "pricingRegion": "EU",
    "accountManager": null,
    "activeCartQid": "b4d6aea2-6169-4c06-abcd-a53c85926aac",
    "pauseReason": null,
    "expectedPauseEnd": null,
    "isSeller": false,
    "saleExpiryWindow": 3,
    "isDeadlineOverrideApplied": false,
    "sellerAcceptedSlaAt": null,
    "canBuyerCheckout": true,
    "personaDistributionChannels": [
      "MARKETPLACES"
    ],
    "annualTurnover": "500K_TO_1M",
    "numberOfEmployees": "FIVE_TO_TWENTY_FIVE",
    "fid": "E81Y9",
    "showOnlyTraceableStock": false,
    "pricingModel": "Offer Based",
    "isMonduOnboarded": false,
    "isOnboarded": true,
    "latestTaxNumber": {
      "countryCode": "FR",
      "taxNumber": "FR29897860847",
      "companyName": "SARL GAUSS",
      "validationStatus": "VALID"
    }
  },
  "signature": "eyJwayI6MTUzMTQ5fQ:1uF7in:Rxm7WRcAyUXDetdMxEf4NKfdnyrjnM802AH7TE44pf0"
}